@References.Api_HostAddress = http://localhost:5154

GET {{References.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{References.Api_HostAddress}}/links
Accept: application/json

###

POST {{References.Api_HostAddress}}/links
Accept: application/json 
Content-Type: application/json
{
    "href": "https://google.com",
    "description": "Google Search Engine"
}

###